### ISSUE TITLE
Unexpected behavior during nextflow run

### ISSUE THREAD

**Issue by bkellman** [matsengrp/phip-flow#66]
I am running the phip-flow pipeline pancov demo using: 
```
nextflow run matsengrp/phip-flow -r V1.11 -profile docker \
        --sample_table ../code/phip-flow/data/pan-cov-example/sample_table_with_beads_and_lib2.csv \
        --peptide_table ../code/phip-flow/data/pan-cov-example/peptide_table.csv \
        --output_tall_csv true \
        --output_wide_csv true \
        --results "$(date -I)" \
        -resume
```
While the run terminated with several outputs, there were also multiple errors.
[nextflow.pancov.test.log.log](https://github.com/matsengrp/phip-flow/files/12481892/nextflow.pancov.test.log.log)
Is this expected behavior? Is this resulting from an incomplete install?

**Comment by bkellman** [comment]
I played around a bit overnight and I think I may have resolved by re-installing BEER. Why would that impact alignment completion?

**Comment by jgallowa07** [comment]
@bkellman Sorry for the headache here. It's hard to tell what going on with the log file when you're using using inputs which are not provided by the repository (sample_table_with_beads_and_lib**2**.csv). I'm assuming your version simply updates the paths (fastq_filepath column) in the [provided sample table](https://github.com/matsengrp/phip-flow/blob/main/data/pan-cov-example/sample_table_with_beads_and_lib.csv) are all relative to `../code/phip_flow/`. 
In any case, it seems the log file you provided is saying the run completed as expected. 
```
 Workflow completed > WorkflowStats[succeededCount=40; failedCount=0
```
Can you specify which errors you are referring to?  When I replicate this directory structure and run the command you supplied above, I get the following log output:

[replicate_run.log](https://github.com/matsengrp/phip-flow/files/12524550/replicate_run.log)

This looks normal/expected to me.

> I played around a bit overnight and I think I may have resolved by re-installing BEER. Why would that impact alignment completion?

You are correct, the installation of BEER should not impact the alignment at all. But you're using the `--profile docker` option, correct? In this case, you should not need to install anything except docker and nexflow. Out publicly hosted containers should handle all dependencies for you.

**Comment by bkellman** [comment]
@jgallowa07 thanks for the quick response and sorry for the delay. I've been stuck at the bench the last few weeks. Returning to the code, I now realize that not every module is supposed to run. I think that was my mistake. 

Thanks for your thorough response and sorry for my mistake.
