### ISSUE TITLE
[improvement] Examples with summarize_by_organism

### ISSUE THREAD

**Issue by bkellman** [matsengrp/phip-flow#67]
Are you able to share any examples that use the summarize_by_organism term? I'm not sure what the "public_epitopes_csv" should look like or how it factors into the analysis.

Thanks!
Ben

**Comment by jgallowa07** [comment]
@sminot Any thoughts here? Personally, I've never interacted with this optional portion of the pipeline.

**Comment by jgallowa07** [comment]
I've added a small patch to the docs giving an example of how to run the workflow with the example data [here](https://matsengrp.github.io/phippery/alignments-pipeline.html#virscan-organism-summary) So I'll close this for now. But if you have any extra thoughts on what else might be useful as you get more familiar feel free to suggest further!
